version: "3.8"
services:
  bookshop-catalog-service:
    depends_on:
      - bookshop-postgres
    image: "bookshop-catalog-service"
    container_name: "bookshop-catalog-service"
    ports:
      - 9001:9001
      - 8001:8001
    environment:
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8001
      - BPL_JVM_THREAD_COUNT=50
      - SPRING_DATASOURCE_URL=jdbc:postgresql://bookshop-postgres:5432/bookshopdb_catalog
      - SPRING_PROFILES_ACTIVE=testdata
      - SPRING_CLOUD_CONFIG_URI=http://bookshop-config-service:8888
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://host.docker.internal:8080/realms/bookshop


  bookshop-order-service:
    depends_on:
      - bookshop-postgres
      - bookshop-rabbitmq
    image: "bookshop-order-service"
    container_name: "bookshop-order-service"
    ports:
      - 9002:9002
      - 8002:8002
    environment:
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8002
      - BOOKSHOP_BOOKSHOP_CATALOG_SERVICE_URI=http://bookshop-catalog-service:9001
      - SPRING_CLOUD_CONFIG_URI=http://bookshop-config-service:8888
      - SPRING_R2DBC_URL=r2dbc:postgresql://bookshop-postgres:5432/bookshopdb_order
      - SPRING_FLYWAY_URL=jdbc:postgresql://bookshop-postgres:5432/bookshopdb_order
      - SPRING_RABBITMQ_HOST=bookshop-rabbitmq
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://host.docker.internal:8080/realms/bookshop

  bookshop-dispatcher-service:
    depends_on:
      - bookshop-rabbitmq
    image: "bookshop-dispatcher-service"
    container_name: bookshop-dispatcher-service
    ports:
      - 9003:9003
      - 8003:8003
    environment:
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8003
      - SPRING_CLOUD_CONFIG_URI=http://bookshop-config-service:8888
      - SPRING_RABBITMQ_HOST=bookshop-rabbitmq

  bookshop-edge-service:
    depends_on:
      - bookshop-redis
      - bookshop-keycloak
      - bookshop-ui
    image: "bookshop-edge-service"
    container_name: "bookshop-edge-service"
    ports:
      - 9000:9000
      - 8000:8000
    environment:
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8000
      - BOOKSHOP_CATALOG_SERVICE_URL=http://bookshop-catalog-service:9001
      - BOOKSHOP_ORDER_SERVICE_URL=http://bookshop-order-service:9002
      - SPRING_CLOUD_CONFIG_URI=http://bookshop-config-service:8888
      - SPRING_REDIS_HOST=bookshop-redis
      - SPA_URL=http://bookshop-ui:9004
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI=http://host.docker.internal:8080/realms/bookshop

  bookshop-config-service:
    image: "bookshop-config-service"
    container_name: "bookshop-config-service"
    ports:
      - 8888:8888
      - 9888:9888
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=9888



  bookshop-postgres:
    image: "postgres:14.4"
    container_name: "bookshop-postgres"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql


  bookshop-redis:
    image: "redis:7.0"
    container_name: "bookshop-redis"
    ports:
      - 6379:6379

  bookshop-rabbitmq:
    image: rabbitmq:3.10-management
    container_name: bookshop-rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf

  bookshop-keycloak:
    image: quay.io/keycloak/keycloak:19.0
    container_name: "bookshop-keycloak"
    command: start-dev --import-realm
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    environment:
      - KEYCLOAK_ADMIN=user
      - KEYCLOAK_ADMIN_PASSWORD=password
    ports:
      - 8080:8080

  bookshop-ui:
    image: "bookshop-ui"
    container_name: "bookshop-ui"
    ports:
      - 9004:9004
    environment:
      - PORT=9004
