include('/Users/dreevo/Documents/workshop/bookshop/bookshop-config-service/Tiltfile')
include('/Users/dreevo/Documents/workshop/bookshop/bookshop-catalog-service/Tiltfile')
include('/Users/dreevo/Documents/workshop/bookshop/bookshop-order-service/Tiltfile')
update_settings(max_parallel_updates=1)